"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 07:28:27.392696
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_text', sa.Text(), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('search_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('registration_url', sa.String(length=1000), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('deadline_note', sa.Text(), nullable=True),
    sa.Column('event_start', sa.Date(), nullable=True),
    sa.Column('event_end', sa.Date(), nullable=True),
    sa.Column('registration_status', sa.String(length=60), nullable=True),
    sa.Column('modality', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.String(length=200), nullable=True),
    sa.Column('prize_text', sa.Text(), nullable=True),
    sa.Column('prize_amount_usd', sa.Integer(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=600), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['search_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_opportunities_deadline', 'opportunities', ['deadline'], unique=False)
    op.create_index('ix_opportunities_discovered_at', 'opportunities', ['discovered_at'], unique=False)
    op.create_table('opportunity_projects',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'project_id')
    )
    op.create_index(op.f('ix_opportunity_projects_project_id'), 'opportunity_projects', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_projects_project_id'), table_name='opportunity_projects')
    op.drop_table('opportunity_projects')
    op.drop_index('ix_opportunities_discovered_at', table_name='opportunities')
    op.drop_index('ix_opportunities_deadline', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('search_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('search_config')
    op.drop_table('projects')
    # ### end Alembic commands ###
